name: Rails CI

on:
  push:
    paths:
      - 'awm-api/**'
      - '.github/**'
  pull_request:
    paths:
      - 'awm-api/**'
      - '.github/**'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bundle
        run: sudo gem install bundler:1.17.2
      - name: Install bundler
        run: |
          cd awm-api
          bundle install --with development
      - name: Rubocop
        run: cd awm-api && bundle exec rubocop
      - name: Rails Best Practices
        run:
          cd awm-api && bundle exec rails_best_practices -e
          "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      - name: Rpec
        run: cd awm-api && bundle exec rspec --format documentation
